---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_enablerepo: "remi,remi-php72"
    php_default_version_debian: "7.2"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Set php_packages for PHP 7.1 Debian install.
      set_fact:
        php_packages:
          - php7.1-common
          - php7.1-cli
          - php7.1-dev
          - php7.1-fpm
          - libpcre3-dev
          - php7.1-opcache
          - php7.1-apcu
      when: ansible_distribution == 'Debian'

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.repo-dotdeb
      when: ansible_distribution == 'Debian'
    - role: geerlingguy.php
    - role: geerlingguy.php-xdebug

  post_tasks:
    - name: Run test script to confirm XDebug is working.
      script: xdebug-test.php
      args:
        executable: php
      changed_when: false
